language: c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew outdated openssl || brew upgrade openssl; brew install libevent mysql sqlite hiredis; find /usr -name 'md5.h' | grep openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; sudo apt-get install -y debhelper dpkg-dev libssl-dev libevent-dev sqlite3 libsqlite3-dev postgresql-client libpq-dev mysql-client libmysqlclient-dev libhiredis-dev; fi

 
matrix:
    include:
        - os: linux
          sudo: required
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode8
          env:
            - CFLAGS = ${CFLAGS} -I/usr/local/Cellar/openssl/1.0.2h_1/include/openssl/
            - LDFLAGS = ${LDFLAGS} -L/usr/local/Cellar/openssl/1.0.2h_1/lib/openssl/ 
        - os: osx
          osx_image: xcode7
        - os: osx
          osx_image: xcode6
    
