language: c

addons:
  apt:
    packages:
      - debhelper 
      - dpkg-dev 
      - libssl-dev 
      - libevent-dev 
      - sqlite3 
      - libsqlite3-dev 
      - postgresql-client 
      - libpq-dev 
      - mysql-client 
      - libmysqlclient-dev 
      - libhiredis-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew outdated openssl || brew upgrade openssl; brew install libevent mysql sqlite hiredis; fi


matrix:
    include:
        - os: linux
          sudo: required
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7
        - os: osx
          osx_image: xcode6
    
