language: c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; brew install libevent mysql sqlite hiredis; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; sudo apt-get install -y debhelper dpkg-dev libssl-dev libevent-dev sqlite3 libsqlite3-dev postgresql-client libpq-dev mysql-client libmysqlclient-dev libhiredis-dev; fi

  
os: 
 - linux 
 - osx
